name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 기본 브랜치명이 'main'인지 확인하세요 (과거에는 'master'인 경우도 있음)

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
